name: Github Actions Maven Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
           
      # Sonar Testing Scan
      #- name: SonarCloud Scan
      #  uses: SonarSource/sonarcloud-github-action@v1.6

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
       #   echo Add other actions to build,
        #  echo test, and deploy your project
      
      # Python installation 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
       
       # Python version check
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      # Upload a Build Artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with :
          name: Artifacts
          path : target/*.jar
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kprbarani99_DemoJavaMaven
      
      ######## JUnit Test with Maven ########
      - name: Test with Maven
        run: mvn -B test --file pom.xml
        
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
